// Mocks generated by Mockito 5.4.5 from annotations
// in accountingmultiplatform/test/mock_accounting_repository.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:accountingmultiplatform/data/accounting.dart' as _i3;
import 'package:accountingmultiplatform/data/accounting_repository.dart' as _i4;
import 'package:accountingmultiplatform/data/total_expenses_of_grouping_tag.dart'
    as _i7;
import 'package:accountingmultiplatform/data/total_expenses_of_month.dart'
    as _i6;
import 'package:built_collection/built_collection.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBuiltList_0<E> extends _i1.SmartFake implements _i2.BuiltList<E> {
  _FakeBuiltList_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccounting_1 extends _i1.SmartFake implements _i3.Accounting {
  _FakeAccounting_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AccountingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountingRepository extends _i1.Mock
    implements _i4.AccountingRepository {
  @override
  _i5.Future<_i2.BuiltList<_i3.Accounting>> queryPreviousAccounting(
    DateTime? lastDate,
    int? limit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#queryPreviousAccounting, [lastDate, limit]),
            returnValue: _i5.Future<_i2.BuiltList<_i3.Accounting>>.value(
              _FakeBuiltList_0<_i3.Accounting>(
                this,
                Invocation.method(#queryPreviousAccounting, [lastDate, limit]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.BuiltList<_i3.Accounting>>.value(
                  _FakeBuiltList_0<_i3.Accounting>(
                    this,
                    Invocation.method(#queryPreviousAccounting, [
                      lastDate,
                      limit,
                    ]),
                  ),
                ),
          )
          as _i5.Future<_i2.BuiltList<_i3.Accounting>>);

  @override
  _i5.Future<Null> insertAccounting(_i3.Accounting? accounting) =>
      (super.noSuchMethod(
            Invocation.method(#insertAccounting, [accounting]),
            returnValue: _i5.Future<Null>.value(),
            returnValueForMissingStub: _i5.Future<Null>.value(),
          )
          as _i5.Future<Null>);

  @override
  _i5.Future<Null> deleteAccountingById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccountingById, [id]),
            returnValue: _i5.Future<Null>.value(),
            returnValueForMissingStub: _i5.Future<Null>.value(),
          )
          as _i5.Future<Null>);

  @override
  _i5.Future<_i3.Accounting> getAccountingById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAccountingById, [id]),
            returnValue: _i5.Future<_i3.Accounting>.value(
              _FakeAccounting_1(
                this,
                Invocation.method(#getAccountingById, [id]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.Accounting>.value(
              _FakeAccounting_1(
                this,
                Invocation.method(#getAccountingById, [id]),
              ),
            ),
          )
          as _i5.Future<_i3.Accounting>);

  @override
  _i5.Future<double> totalExpensesOfDay(int? millisecondsSinceEpoch) =>
      (super.noSuchMethod(
            Invocation.method(#totalExpensesOfDay, [millisecondsSinceEpoch]),
            returnValue: _i5.Future<double>.value(0.0),
            returnValueForMissingStub: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);

  @override
  _i5.Future<_i2.BuiltList<_i6.TotalExpensesOfMonth>> getMonthTotalAmount([
    DateTime? latestMonth,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getMonthTotalAmount, [latestMonth]),
            returnValue:
                _i5.Future<_i2.BuiltList<_i6.TotalExpensesOfMonth>>.value(
                  _FakeBuiltList_0<_i6.TotalExpensesOfMonth>(
                    this,
                    Invocation.method(#getMonthTotalAmount, [latestMonth]),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.BuiltList<_i6.TotalExpensesOfMonth>>.value(
                  _FakeBuiltList_0<_i6.TotalExpensesOfMonth>(
                    this,
                    Invocation.method(#getMonthTotalAmount, [latestMonth]),
                  ),
                ),
          )
          as _i5.Future<_i2.BuiltList<_i6.TotalExpensesOfMonth>>);

  @override
  _i5.Future<_i2.BuiltList<_i7.TotalExpensesOfGroupingTag>>
  getGroupingTagOfLatestMonth(DateTime? latestMonth) =>
      (super.noSuchMethod(
            Invocation.method(#getGroupingTagOfLatestMonth, [latestMonth]),
            returnValue:
                _i5.Future<_i2.BuiltList<_i7.TotalExpensesOfGroupingTag>>.value(
                  _FakeBuiltList_0<_i7.TotalExpensesOfGroupingTag>(
                    this,
                    Invocation.method(#getGroupingTagOfLatestMonth, [
                      latestMonth,
                    ]),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.BuiltList<_i7.TotalExpensesOfGroupingTag>>.value(
                  _FakeBuiltList_0<_i7.TotalExpensesOfGroupingTag>(
                    this,
                    Invocation.method(#getGroupingTagOfLatestMonth, [
                      latestMonth,
                    ]),
                  ),
                ),
          )
          as _i5.Future<_i2.BuiltList<_i7.TotalExpensesOfGroupingTag>>);

  @override
  _i5.Future<_i2.BuiltList<_i7.TotalExpensesOfGroupingTag>>
  getGroupingMonthTotalAmount(DateTime? dateTime) =>
      (super.noSuchMethod(
            Invocation.method(#getGroupingMonthTotalAmount, [dateTime]),
            returnValue:
                _i5.Future<_i2.BuiltList<_i7.TotalExpensesOfGroupingTag>>.value(
                  _FakeBuiltList_0<_i7.TotalExpensesOfGroupingTag>(
                    this,
                    Invocation.method(#getGroupingMonthTotalAmount, [dateTime]),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.BuiltList<_i7.TotalExpensesOfGroupingTag>>.value(
                  _FakeBuiltList_0<_i7.TotalExpensesOfGroupingTag>(
                    this,
                    Invocation.method(#getGroupingMonthTotalAmount, [dateTime]),
                  ),
                ),
          )
          as _i5.Future<_i2.BuiltList<_i7.TotalExpensesOfGroupingTag>>);
}
