pub_cache: &pub_cache
    folder: ~/.pub-cache

build_cache: &build_cache
  folder: ./build

osx_instance:
  image: mojave-xcode-10.2-flutter

task: 
  name: Running flutter doctor
  - *pub_cache
  flutter_doctor_script: flutter doctor

task:
  name: Checking dart code style
  - *pub_cache
  dartfmt_script: bash ci/dartfmt_check.sh

task:
  name: Running Flutter build runner
  - *pub_cache
  depends_on:
    - Running flutter doctor
    - Checking dart code style
  build_runner_script: 
    - flutter packages get
    - flutter packages pub run build_runner build --delete-conflicting-outputs

task: 
  name: Running flutter test
  - *pub_cache
  depends_on:
    - Running Flutter build runner
  flutter_test_script: flutter test

  task: 
  name: Common module build
  - *build_cache
  depends_on:
    - Running flutter test
  common_module_build_script: 
    - cd android
    - ./gradlew :common:build

task: 
  name: Building android apk
  - *build_cache
  - *pub_cache
  depends_on:
    - Common module build
  flutter_build_apk_script: flutter -v build apk

task: 
  name: Building ios in debug mode without code sign
  - *build_cache
  - *pub_cache
  depends_on:
    - Common module build
  # https://github.com/flutter/flutter/issues/24078
  flutter_build_ios_debug_script: flutter build ios --debug --no-codesign --simulator