pub_cache: &pub_cache
  pub_cache:
    folder: ~/.pub-cache
    fingerprint_script: cat pubspec.lock

build_cache: &build_cache
  build_cache:
    folder: ./build

build_runner_code_cache: &build_runner_code_cache
  build_runner_code_cache:
    folder: .
    fingerprint_script: echo ${CIRRUS_BRANCH}-${CIRRUS_CHANGE_IN_REPO}

container:
  image: cirrusci/flutter:latest

flutter_doctor_task: 
  <<: *pub_cache
  flutter_doctor_script: flutter doctor

check_dart_code_style_task:
  <<: *pub_cache
  dartfmt_script: bash ci/dartfmt_check.sh
    
flutter_test_task: 
  <<: *pub_cache
  <<: *build_runner_code_cache
  <<: *build_cache
  depends_on:
    - flutter_doctor
    - check_dart_code_style
  flutter_test_script: 
    - flutter packages get
    - flutter packages pub run build_runner build --delete-conflicting-outputs
    - flutter test

kmpp_common_module_build_task: 
  osx_instance:
    image: mojave-xcode-10.2-flutter
  <<: *build_cache
  <<: *pub_cache
  <<: *build_runner_code_cache
  depends_on:
    - flutter_test
  common_module_build_script: 
    - flutter doctor
    - flutter packages get
    - flutter packages pub run build_runner build --delete-conflicting-outputs
    - cd android
    - ./gradlew :common:build

flutter_build_android_apk_task: 
  <<: *build_cache
  <<: *pub_cache
  <<: *build_runner_code_cache
  depends_on:
    - kmpp_common_module_build
  flutter_build_apk_script: flutter -v build apk

flutter_build_ios_debug_no_codesign_task: 
  osx_instance:
    image: mojave-xcode-10.2-flutter
  <<: *build_cache
  <<: *pub_cache
  <<: *build_runner_code_cache
  depends_on:
    - kmpp_common_module_build
  # https://github.com/flutter/flutter/issues/24078
  flutter_build_ios_debug_script: 
    - pod repo update
    - flutter build ios --debug --no-codesign --simulator