version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: Checking dart code style
          command: |
              bash .circleci/dartfmt_check.sh
      - run:
          name: Running build runner
          command: |
            flutter packages get
            flutter packages pub run build_runner build --delete-conflicting-outputs
      - run:
          name: Running flutter doctor
          command: flutter doctor
      - run:
          name: Running flutter test
          command: flutter test
      - run:
          name: Building android apk
          command: |
              flutter -v build apk

workflows:
  version: 2

  build_and_test:
    jobs:
      - build


